### PR TITLE
Stage 1

### PR DESCRIPTION
**Pull request by rawisa**

### CODE REVIEW

**Comment by robi-y** [comment]
Hi,
This is very detailed, excellent work
A few comments:
- I don't see use of the issues system to plan and coordinate work
- Add subsection headers according to task instructions (resources, development process, etc.)
- Please point to the references of the images used
- In case of long tests taken from the project's site - just wrrite a summary and give a direct link for the rest
  Let me know when we can merge and finish this stage, but do continue on next one.
  Good luck, R.

**Comment by rawisa** [comment]
1) "I don't see use of the issues system to plan and coordinate work", I dont think we need an issues system since we are only 2 members in the team, we both doing every stage together, what do you say ?
2) "In case of long tests taken from the project's site..." What tests ?

**Comment by robi-y** [comment]
1. at least use it minimally for planning your work
2. tests -> texts

**Comment by rawisa** [comment]
Done fixes, let me know what you think.

**Pull request merged**
