### PR TITLE
Stage 1 -intro

### PR DESCRIPTION
**Pull request by adirel**

### CODE REVIEW

**Comment by robi-y** [comment]
Some comments:
Add the project's logo at the top
if you quote from the project's page (e.g., intro, process subsection) please mention and reference it. 
Process subsection - the 2nd statements seems not relevant.
Resources: we look for resources concerning the modeling and architecture of this project - the whole section should be revised

**Comment by adirel** [comment]
ok, notes taken . will repair and send new pull request
about the resources - some of the resources that we mentioned was critical
such as cerum certificate which is part of the customers-product
relationship
we added a few reviews/posts which was allso contributed the development
proccess/model.
(נקודה למחשבה)

2016-05-24 12:18 GMT+03:00 robi-y notifications@github.com:

**Comment by adirel** [comment]
fixes

**Comment by robi-y** [comment]
" and I would love for there to be a community of volunteers around OptiKey"
again, if you quote, say it and put in context
I Still do not understand the beginning of resources section and it's
relevane

**Comment by adirel** [comment]
Ok :) i guess we didnt understand the question.
בתאריך 24 במאי 2016 6:50 אחה״צ,‏ "robi-y" notifications@github.com כתב:

> " and I would love for there to be a community of volunteers around
> OptiKey"
> again, if you quote, say it and put in context
> I Still do not understand the beginning of resources section and it's
> relevane
>

**Comment by robi-y** [comment]
The critical resources you mentioned might be suitable for current phase as part of the stakeholder analysys

**Comment by adirel** [comment]
we fixed the resources review

**Comment by adirel** [comment]
final change on indroduction

**Comment by robi-y** [comment]
Much better, what about the 'development process' subsection? shorten the title and work on the content too - what is the 1st sentence? did you copy if from somewhere? you can use here the sentence in the next subsection about resources

**Comment by adirel** [comment]
development process' subsection
we finished to edit this section followed by your notes... 
we finished stage 1 completely
thank you

**Pull request merged**
