### PR TITLE
Ilanandadir

### PR DESCRIPTION
**Pull request by adirel**
ok

### CODE REVIEW

**Comment by robi-y** [comment]
I don't see a new PR from you - have you submitted phase 1?

**Comment by adirel** [comment]
No ill submit today. Thanks

**Comment by adirel** [comment]
hi robi , we deside to send you today after finishing in class.
can you confirm that you recived my pull request ?

**Comment by robi-y** [comment]
I guess it is this one: #12 ?

**Comment by adirel** [comment]
Yes
בתאריך 24 במאי 2016 12:01 אחה״צ,‏ "robi-y" notifications@github.com כתב:

**Pull request closed without merging**
