### PR TITLE
Update viewsandprespectives.md 

### PR DESCRIPTION
**Pull request by adirel**
thank you.

### CODE REVIEW

**Comment by adirel** [comment]
OK

**Comment by robi-y** [comment]
Some comments:
- missing stakeholders view
- try sending the activity diagram for the developer review
- Looking for some nice modeling, e.g., sequence diagram for the SDK for adding a camera
- Features and challenges: add in header the source of information
- Localization: why do we need the list?

**Comment by robi-y** [comment]
??

**Comment by adirel** [comment]
we are fixing this issues and will send you the result very soon

2016-06-14 10:37 GMT+03:00 robi-y notifications@github.com:

**Comment by adirel** [comment]
hi yagel, we added all fixes. and few interesting parts such as issue talking about modeling with otikey creator

**Comment by robi-y** [comment]
very nice, just improve titles

**Pull request merged**
