### PR TITLE
Stage 1 

### PR DESCRIPTION
**Pull request by rivkage**

### CODE REVIEW

**Comment by robi-y** [comment]
Hello,
Over all the introduction is fine. 2 remarks:
- Please add subsection headers like: development cycles, resources, etc
- If you copy pasted text please start with a direct link and say you are quoting from there.

Also in your issues I only see stages but not real active work.
Let me know when I can merge it and close this phase.

**Comment by robi-y** [comment]
Please comment what has changed?

**Comment by rivkage** [comment]
Hie,

**Comment by rivkage** [comment]
Hie

**Comment by rivkage** [comment]
Hi,
On stage1, we have added new graphs (stats, bugs and features list) and detailed it according to the new elements.
We have commited stage 2 also. It starts from "the beef project documentation" till the end.

**Comment by robi-y** [comment]
Remarks:
Development cycle - just link to the relevant info (and mention their monthly cycle)
add source for high level diagram
improve title for modeling part

**Comment by rivkage** [comment]
I have updated what you asked for.

Thank you,

**Comment by robi-y** [comment]
Hello Team,
I've read your chapter. It is on the way to become a very good one.
Stage 1:
Since it seem they have a detailed documentation in the wiki, you should add a specific link to it.
Stage 2:
- Code structure, you mention that it is complicated to add a new module. So maybe your contribution can be in writing a guide for it (possible with some helper diagrams). You can also mention that for stage 3 that handles maintainability
- Very nice stakeholder analysis! I don't think the flow diagram add match - this is the regular open source process. I think there are other stakeholders like browser vendors, browser users(?) and real attacker - so it will be nice to handle them too.
- even after reading the whole chapter, I think you should add some short explanations to the UML diagrams
  I'll merge it, but let me know if you like to imprve

**Pull request merged**
