### PR TITLE
1

### PR DESCRIPTION
**Pull request by harella1**

### CODE REVIEW

**Comment by robi-y** [comment]
Hello Team,
I see you'r already deep into stage 2 materials but first please finish introduction of stage 1 according to [instructions](https://github.com/jce-il/sw-modeling-2016b/blob/master/Homework.md#stage-1---introducion): project fit, development process and modeling resources.

**Comment by pabloli** [comment]
We have a question:
Project fit: We need to write down why we decide to analyze this Github Repo or why they (Video.Js) develop this module?

**Comment by robi-y** [comment]
a
You're telling the reader why this project was chosen to be analysed in our book

**Comment by pabloli** [comment]
Ok

Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.5.31&pv=4.4.2&source=email_footer_2] On Wed, May 25, 2016 at 3:26 PM, robi-y < notifications@github.com [notifications@github.com] > wrote:
a
You're telling the reader why this project was chosen to be analysed in our book

**Comment by robi-y** [comment]
Anything new to check?

**Comment by pabloli** [comment]
Hi @robi-y,
I'm pull requesting our project for now, 
We worked on:
- the project uses (how to use video.js section)  how & who
- the project code analisys (as i showed you on class) we get the classes diagrams, 
- We start on metrication of the project (we till don't know how to do that)
- We explained the test method.
- If you accept we want to try to pull this chapter on the video.js repo as is

**Note:** we are working over all the states at the same time, because is more easy for us,
Good Week
@pabloli

**Pull request merged**
